/**
 * Example seed prompts for the AI Brief Orchestrator.
 *
 * AUTOGENERATED — do not edit by hand. Source of truth lives in
 * `examples/campaigns/<slug>/seed-prompt.md` (the first fenced code
 * block of each file). Regenerate with:
 *
 *     REGEN_EXAMPLE_PROMPTS=1 npx vitest run __tests__/regen-example-prompts.test.ts
 *
 * The frontend `BriefGeneratorAI` component imports `EXAMPLE_SEEDS` to
 * power the "Load example" secondary button — picks one at random and
 * paste-fills the textarea. No API call, no LLM, no runtime FS read.
 */

export interface ExampleSeed {
  /** Folder name under examples/campaigns/ */
  slug: string;
  /** Stable id from brief.json campaign.id */
  campaignId: string;
  /** Human-readable name from brief.json campaign.name */
  campaignName: string;
  /** Paste-ready seed prompt — extracted from seed-prompt.md, ≤1000 chars */
  prompt: string;
}

export const EXAMPLE_SEEDS: readonly ExampleSeed[] = [
  {
    slug: "coastal-sun-protection",
    campaignId: "coastal-sun-protection-summer-2026",
    campaignName: "Coastal Sun Protection — Summer 2026",
    prompt: "We're running a summer 2026 sun-protection launch for Coastal Wellness Co. Two products: the SPF 50 Mineral Sunscreen — reef-safe, zinc-oxide, water-resistant 80 minutes, broad spectrum — and the After-Sun Cooling Aloe Gel, which is organic aloe vera with vitamin E and cucumber extract. The campaign message is \"Stay Protected All Summer\". Target is North American health-conscious adults 25 to 45, outdoor and beach lifestyle. Tone should be warm, coastal, trustworthy, premium but approachable. I need all three aspect ratios — 1:1, 9:16, and 16:9.",
  },
  {
    slug: "fall-coffee-launch",
    campaignId: "ember-roast-fall-launch",
    campaignName: "Ember Roast — Fall Single-Origin Launch",
    prompt: "Launch Ember Roast, our small-batch single-origin Ethiopia Yirgacheffe coffee, for specialty coffee enthusiasts in their 30s and 40s in the Pacific Northwest who appreciate origin storytelling and slow craft. Tasting notes are bright citrus, jasmine florals, and a honey finish — roasted weekly in Portland, sold in compostable bags. Tone is warm, artisanal, and intimate, leaning into golden-hour cinematic and the slow-living aesthetic. This is a fall launch. Tagline idea: \"Roasted slow. Drink it slower.\"",
  },
  {
    slug: "spring-wellness-launch",
    campaignId: "lumen-spring-reset-2026",
    campaignName: "Lumen — Spring Reset Collection",
    prompt: "Launch Lumen's Spring Reset Collection — three skincare products for ingredient-conscious millennials and Gen X in North America and Europe who like clinical-but-natural brands. The lineup is a 15% L-ascorbic acid Vitamin C Brightening Serum with ferulic acid and vitamin E, a triple-weight Hyaluronic Hydration Mist with rose water and aloe in a recyclable aluminum bottle, and a 10% Niacinamide Pore Refining Cream with zinc PCA and green tea extract. Vegan, dermatologist-tested, fragrance-free where it matters. Tone is fresh, dewy, soft-light studio — science meets botanical. Spring launch. Tagline: \"Wake up your skin. Spring starts here.\"",
  },
  {
    slug: "summer-festival-energy-drink",
    campaignId: "voltcraft-summer-festival-2026",
    campaignName: "Voltcraft — Festival Season Activation",
    prompt: "Activate Voltcraft for the summer festival circuit in North America — Gen Z and younger millennials in their late teens through twenties, EDM and indie scene, energy drink and adaptogen-curious. Two SKUs lead the activation: Surge in Tropical Storm flavor with 200mg natural caffeine, 1g L-theanine for clean focus, and an electrolyte blend; and Glow in Berry Lightning with ashwagandha, B-vitamin complex, and real berry juice for sustained six-hour energy. Both are zero sugar, zero crash. Visual direction is high-energy neon, electric, night-scene cinematic, vibrant gradients, motion-blur kinetic — think main-stage at 1am. Tagline: \"All night. Every set. Zero crash.\"",
  },
  {
    slug: "winter-streetwear-drop",
    campaignId: "northgrid-winter-drop-2026",
    campaignName: "Northgrid — Winter Technical Drop",
    prompt: "Drop a winter technical streetwear collection from Northgrid for urban Gen Z and millennial commuters in Northeast US cities — design-literate, into all-weather layering and premium technical fabrics. Two pieces lead the drop: a 3-layer waterproof Stormshell parka with seam-taped construction and recycled face fabric, and the Thermal Cargo Pant with Primaloft insulation, windproof front panels, and zip thigh pockets. Tone should feel moody, editorial, high-contrast, with a cold blue-grey palette — premium streetwear, not athleisure. Tagline: \"Built for the city that doesn't slow down.\"",
  },
] as const;

/**
 * Pick one example seed at random.
 *
 * Used by the "Load example" button. Pure function — pass `Math.random`
 * (or a seeded RNG in tests) so the picker stays deterministic when
 * needed.
 */
export function pickRandomSeed(rng: () => number = Math.random): ExampleSeed {
  if (EXAMPLE_SEEDS.length === 0) {
    throw new Error(
      "pickRandomSeed: EXAMPLE_SEEDS is empty — run the regen test to populate it."
    );
  }
  const i = Math.floor(rng() * EXAMPLE_SEEDS.length);
  // Non-null assertion is safe — i is bounded by the length check above.
  return EXAMPLE_SEEDS[i]!;
}
